@startuml
set separator none
title Book Management System - Containers

left to right direction

skinparam {
  arrowFontSize 10
  defaultTextAlignment center
  wrapWidth 200
  maxMessageSize 100
}

hide stereotype

skinparam rectangle<<BookManagementSystem.APIApplication>> {
  BackgroundColor #55aa55
  FontColor #000000
  BorderColor #3b763b
  shadowing false
}
skinparam person<<Administrator>> {
  BackgroundColor #116611
  FontColor #000000
  BorderColor #0b470b
  shadowing false
}
skinparam database<<BookManagementSystem.Database>> {
  BackgroundColor #0066cc
  FontColor #000000
  BorderColor #00478e
  shadowing false
}
skinparam person<<EndUser>> {
  BackgroundColor #116611
  FontColor #000000
  BorderColor #0b470b
  shadowing false
}
skinparam rectangle<<BookManagementSystem.WebApplication>> {
  BackgroundColor #55aa55
  FontColor #000000
  BorderColor #3b763b
  shadowing false
}
skinparam rectangle<<BookManagementSystem>> {
  BorderColor #1f5f1f
  FontColor #1f5f1f
  shadowing false
}

person "==End User\n<size:10>[Person]</size>\n\nA person who uses the application to browse and manage books." <<EndUser>> as EndUser
person "==Administrator\n<size:10>[Person]</size>\n\nA person who manages books and categories." <<Administrator>> as Administrator

rectangle "Book Management System\n<size:10>[Software System]</size>" <<BookManagementSystem>> {
  database "==Database\n<size:10>[Container: Stores books, categories, reviews, users, and tokens.]</size>\n\nSQLite" <<BookManagementSystem.Database>> as BookManagementSystem.Database
  rectangle "==Web Application\n<size:10>[Container: React + Vite]</size>\n\nDelivers the user interface of the application and consumes the API." <<BookManagementSystem.WebApplication>> as BookManagementSystem.WebApplication
  rectangle "==API Application\n<size:10>[Container: Node.js]</size>\n\nHandles application logic and exposes functionality via a JSON/HTTPS API." <<BookManagementSystem.APIApplication>> as BookManagementSystem.APIApplication
}

EndUser .[#707070,thickness=2].> BookManagementSystem.WebApplication : "<color:#707070>Accesses books, adds comments and reviews, saves favorite books"
Administrator .[#707070,thickness=2].> BookManagementSystem.WebApplication : "<color:#707070>Manages books and categories"
BookManagementSystem.WebApplication .[#707070,thickness=2].> BookManagementSystem.APIApplication : "<color:#707070>Makes API calls to\n<color:#707070><size:8>[REST API]</size>"
BookManagementSystem.APIApplication .[#707070,thickness=2].> BookManagementSystem.Database : "<color:#707070>Reads from and writes to"
@enduml