@startuml
set separator none

skinparam {
  shadowing false
  arrowFontSize 15
  defaultTextAlignment center
  wrapWidth 100
  maxMessageSize 100
}
hide stereotype

skinparam rectangle<<_transparent>> {
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}

skinparam person<<1>> {
  BackgroundColor #116611
  FontColor #000000
  BorderColor #0b470b
}
person "==Person" <<1>>

skinparam rectangle<<2>> {
  BackgroundColor #2d882d
  FontColor #000000
  BorderColor #1f5f1f
}
rectangle "==Software System" <<2>>

rectangle "." <<_transparent>> as 3
3 .[#707070,thickness=2].> 3 : "<color:#707070>Relationship"


@enduml