@startuml
set separator none

skinparam {
  shadowing false
  arrowFontSize 15
  defaultTextAlignment center
  wrapWidth 100
  maxMessageSize 100
}
hide stereotype

skinparam rectangle<<_transparent>> {
  BorderColor transparent
  BackgroundColor transparent
  FontColor transparent
}

skinparam rectangle<<1>> {
  BackgroundColor #88cc88
  FontColor #000000
  BorderColor #5f8e5f
}
rectangle "==Component" <<1>>

skinparam database<<2>> {
  BackgroundColor #93c6e5
  FontColor #000000
  BorderColor #668aa0
}
database "==Container, Database" <<2>>

rectangle "." <<_transparent>> as 3
3 .[#707070,thickness=2].> 3 : "<color:#707070>Relationship"


@enduml